-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 14:53:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema doeajudebd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doeajudebd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doeajudebd` DEFAULT CHARACTER SET utf8mb4 ;
USE `doeajudebd` ;

-- -----------------------------------------------------
-- Table `doeajudebd`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doeajudebd`.`usuario` ;

CREATE TABLE IF NOT EXISTS `doeajudebd`.`usuario` (
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nomeCompleto` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cpf_UNIQUE` ON `doeajudebd`.`usuario` (`cpf` ASC);


-- -----------------------------------------------------
-- Table `doeajudebd`.`publicacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doeajudebd`.`publicacao` ;

CREATE TABLE IF NOT EXISTS `doeajudebd`.`publicacao` (
  `idpublicacao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(12) NULL,
  `foto` VARCHAR(150) NULL,
  `status` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  `usuario_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idpublicacao`),
  CONSTRAINT `fk_publicacao_usuario`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `doeajudebd`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_publicacao_usuario_idx` ON `doeajudebd`.`publicacao` (`usuario_email` ASC);


-- -----------------------------------------------------
-- Table `doeajudebd`.`interesse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `doeajudebd`.`interesse` ;

CREATE TABLE IF NOT EXISTS `doeajudebd`.`interesse` (
  `idinteresse` INT NOT NULL AUTO_INCREMENT,
  `usuario_email` VARCHAR(100) NOT NULL,
  `publicacao_idpublicacao` INT NOT NULL,
  PRIMARY KEY (`idinteresse`),
  CONSTRAINT `fk_interesse_usuario1`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `doeajudebd`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interesse_publicacao1`
    FOREIGN KEY (`publicacao_idpublicacao`)
    REFERENCES `doeajudebd`.`publicacao` (`idpublicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_interesse_usuario1_idx` ON `doeajudebd`.`interesse` (`usuario_email` ASC);

CREATE INDEX `fk_interesse_publicacao1_idx` ON `doeajudebd`.`interesse` (`publicacao_idpublicacao` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
