-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 14:10:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nomeCompleto` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`publicacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`publicacao` (
  `idpublicacao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(150) NULL,
  `status` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `usuario_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idpublicacao`),
  INDEX `fk_publicacao_usuario_idx` (`usuario_email` ASC) ,
  CONSTRAINT `fk_publicacao_usuario`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `mydb`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interesse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`interesse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`interesse` (
  `idinteresse` INT NOT NULL AUTO_INCREMENT,
  `usuario_email` VARCHAR(100) NOT NULL,
  `publicacao_idpublicacao` INT NOT NULL,
  PRIMARY KEY (`idinteresse`),
  INDEX `fk_interesse_usuario1_idx` (`usuario_email` ASC) ,
  INDEX `fk_interesse_publicacao1_idx` (`publicacao_idpublicacao` ASC) ,
  CONSTRAINT `fk_interesse_usuario1`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `mydb`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interesse_publicacao1`
    FOREIGN KEY (`publicacao_idpublicacao`)
    REFERENCES `mydb`.`publicacao` (`idpublicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
