-- MySQL Script generated by MySQL Workbench
-- Mon Sep 30 14:34:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `cpf` INT NOT NULL,
  `nomeCompleto` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacao` (
  `id_publicacao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `foto` VARCHAR(150) NULL,
  `contato` VARCHAR(100) NULL,
  `status` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `fk_usuario` INT NOT NULL,
  PRIMARY KEY (`id_publicacao`, `fk_usuario`),
  INDEX `fk_publicacao_usuario1_idx` (`fk_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_publicacao_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interesse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interesse` (
  `id_interesse` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NOT NULL,
  `fk_publicacao` INT NOT NULL,
  PRIMARY KEY (`id_interesse`, `fk_usuario`, `fk_publicacao`),
  INDEX `fk_interesse_usuario_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_interesse_publicacao1_idx` (`fk_publicacao` ASC) VISIBLE,
  CONSTRAINT `fk_interesse_usuario`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interesse_publicacao1`
    FOREIGN KEY (`fk_publicacao`)
    REFERENCES `mydb`.`publicacao` (`id_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
